### ISSUE TITLE
HTML5, CSS5 웹디자인 서적

### ISSUE THREAD

**Issue by mvcweb75** [mvcweb75/bookdesign#1]
첫번째 출판예정인 웹디자인 서적의 내용 기획

**Comment by ankyungmin** [comment]
디자인을 어떻게 하면 좋을지 함께 생각해보면 좋겠어요

**Comment by mvcweb75** [comment]
우선 디자인에 필요한 이미지는 사진의 경우 직접 디카로 찍어야 할거 같아요.
왜냐하면 저작권 문제가 있거든요.
그리고 일러스트나 포토샵을 이용해서 직접 드로잉한 이미지를 사용하는 것은 어떨까요? #
